sudo: required
services:
    - docker

before_install:
    - docker build -t lwlach/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true lwlach/react-test npm test

after_success:
    - docker build -t lwlach/multi-client ./client
    - docker build -t lwlach/multi-nginx ./nginx
    - docker build -t lwlach/multi-server ./server
    - docker build -t lwlach/multi-worker ./worker 

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push lwlach/multi-client
    - docker push lwlach/multi-nginx
    - docker push lwlach/multi-server
    - docker push lwlach/multi-worker

deploy:
    provider: elasticbeanstalk
    region: sa-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-sa-east-1-851852919520
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
